language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - PREMAKE_CC=gcc
    - os: linux
      compiler: clang
      env:
        - PREMAKE_CC=clang

install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz -O premake.tar.gz
  - tar -xf premake.tar.gz
  - ./premake5 --cc=$PREMAKE_CC gmake
  - cd build/gmake_$PREMAKE_CC

script:
  make
