name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2
    - name: Install premake
      run: |
         wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz -O premake.tar.gz
         tar -xf premake.tar.gz
    - name: Run premake
      run: |
        ./premake5 --cc=${{matrix.compiler}} gmake
    - name: Build
      run: |
        cd build/gmake_${{matrix.compiler}}
        make

  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64]
    steps:
    - uses: actions/checkout@v2
    - name: Run premake
      shell: powershell
      run: |
        .\bin\windows\premake5.exe vs2019
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build
      shell: cmd
      run: |
        msbuild build\vs2019\objzero.sln /p:Configuration=Release /p:Platform="${{matrix.platform}}" /verbosity:minimal
